# Generated by Django 5.0.3 on 2024-04-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='launch_date',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='MissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('reddit_link', models.URLField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
            ],
        ),
    ]
